[build]
builder = "nixpacks"

[deploy]
startCommand = "bin/server"
healthcheckPath = "/"
healthcheckTimeout = 30
restartPolicyType = "on_failure"

[[deploy.environmentVariables]]
name = "GIN_MODE"
value = "release"
